[package]
org = "tharmigan"
name = "persist_connection_demo"
version = "0.1.0"
distribution = "2201.13.1"
title = "Persist Connection Demo"

[build-options]
sticky = true

[[dependency]]
org = "ballerina"
name = "tool.persist"
version = "1.9.1"

[[tool.persist]]
id = "persist_connection_demo.publishingDB"
targetModule = "persist_connection_demo.publishingDB"
filePath = "persist/publishingDB/model.bal"
options.datastore = "postgresql"
options.eagerLoading = true
options.withInitParams = true

[[tool.persist]]
id = "persist_connection_demo.contentDB"
targetModule = "persist_connection_demo.contentDB"
filePath = "persist/contentDB/model.bal"
options.datastore = "mysql"
options.eagerLoading = true
options.withInitParams = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.7.2"
